### ISSUE TITLE
Prepare project for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/management-api#27]
### Tasks

- [ ] Update text files
- [ ] Generate "boilerplate" specification project
- [ ] Make a staging release
- [ ] Generate Stand-alone TCK test results
- [ ] Submit tests for ballot
- [ ] Release to Maven Central

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by starksm64** [comment]
Updating text files
